fix: fix error during project.groovy plugin application
```
org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply
plugin [class 'org.fidata.gradle.JVMBasePlugin']
Caused by: org.gradle.api.plugins.UnknownPluginException: Plugin with type
class org.fidata.gradle.GroovyBasePlugin has not been used.
```