fix(base.jvm): fix public releases for subprojects
```
org.gradle.api.UnknownDomainObjectException: Extension of type
'SemanticReleasePluginExtension' does not exist.
```